imports:
    - { resource: normalizers.yml }
    - { resource: encoders.yml }


services:

    #
    # Normalizer requirements
    #

    ms.property_info.extractor.reflection:
        class: Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor

    ms.property_info.extractor:
        class: Symfony\Component\PropertyInfo\PropertyInfoExtractor
        arguments: [ [], [ "@ms.property_info.extractor.reflection" ] ]
